In [22]:
import warnings

from toolz import valmap

import h5py
import pyharm

import numpy as np

from decimal import Decimal

In [25]:
def get_statistics(file, quality):
    """
    file: the file storing data
    quality: string, the quality whose statistics we want 
    """
    print('statistics on ' + quality + ':')
    print('max ' + quality + ':')
    maximum = np.max(file)
    print("{:e}".format(maximum))
    print('min ' + quality + ':')
    minimum = np.min(file)
    print("{:e}".format(minimum))
    # decimal_array_3d = np.array([[[Decimal(str(x)) for x in row] for row in matrix] for matrix in file])
    print('percentile on ' + quality+ ' [25%, 50%, 75%]:')
    # percentile of the flattened grid
    percentile1 = np.percentile(file, [25, 50, 75])
    print(percentile1)
    print('percentile on ' + quality+ ' [10%, 90%]:')
    # percentile of the flattened grid
    percentile2 = np.percentile(file, [10, 90])
    print(percentile2)

In [3]:
# some constants
cl = 29979245800.0 # speed of light in cgs
mp = 1.67262171e-24
kb = 1.3806505e-16
mu = 1.

<h5>MAD, $R_{h}=1$, order of magnitude check</h5>

var(Te)

In [4]:
varTe_file = np.load('ma_rh1_varTe.npy', allow_pickle=True)
type(varTe_file)

numpy.ndarray

In [5]:
varTe_file

array([[[1.03307531e+22, 9.59489767e+21, 8.97971798e+21, ...,
         9.69158436e+21, 9.53630782e+21, 1.10374333e+22],
        [6.99398270e+21, 5.67227738e+21, 4.16023777e+21, ...,
         5.53396092e+21, 6.26557493e+21, 7.32337271e+21],
        [1.96069033e+22, 1.80792574e+22, 1.54185368e+22, ...,
         1.79353980e+22, 2.06240251e+22, 2.05680149e+22],
        ...,
        [2.20593512e+22, 2.67640441e+22, 2.29057119e+22, ...,
         1.86381657e+22, 1.94861690e+22, 1.94252536e+22],
        [4.34826833e+21, 4.12514671e+21, 4.41137439e+21, ...,
         7.82474332e+21, 6.32459538e+21, 4.96361407e+21],
        [1.50357963e+22, 1.23297971e+22, 1.07640540e+22, ...,
         1.94333217e+22, 1.74873299e+22, 1.68800646e+22]],

       [[1.45542214e+22, 1.43568525e+22, 1.26462276e+22, ...,
         1.38153930e+22, 1.32666021e+22, 1.45182950e+22],
        [1.29279520e+22, 8.80130456e+21, 6.15378048e+21, ...,
         9.92610407e+21, 9.54682388e+21, 1.24620401e+22],
        [1.90848397e+22, 

In [26]:
get_statistics(varTe_file, 'var(Te)')

statistics on var(Te):
max var(Te):
1.188983e+25
min var(Te):
5.143357e+07
percentile on var(Te) [25%, 50%, 75%]:
[1.38530551e+17 3.53759937e+19 9.98166726e+21]
percentile on var(Te) [10%, 90%]:
[1.22748139e+15 3.90330603e+22]


In [28]:
print(np.percentile(varTe_file, [35, 40, 45]))

[9.77051650e+17 2.74637513e+18 8.33477099e+18]


var(Pg)

In [7]:
varPg_file = np.load('ma_varPg.npy', allow_pickle=True)
type(varPg_file)

numpy.ndarray

In [8]:
varPg_file

array([[[8.51708670e-04, 7.96927959e-04, 7.28750962e-04, ...,
         7.00501770e-04, 7.47138430e-04, 8.45693732e-04],
        [3.57777506e-04, 3.53933232e-04, 3.20445689e-04, ...,
         3.33507020e-04, 3.16553869e-04, 3.35466821e-04],
        [5.74580708e-04, 6.04842153e-04, 5.55854355e-04, ...,
         4.90998792e-04, 4.50757989e-04, 4.72065142e-04],
        ...,
        [5.09149189e-04, 5.24218600e-04, 5.22115694e-04, ...,
         5.95662780e-04, 6.01329835e-04, 5.65183251e-04],
        [4.35495945e-04, 4.25131753e-04, 3.79630096e-04, ...,
         3.14392483e-04, 2.68713446e-04, 3.30469734e-04],
        [8.01985223e-04, 7.63913080e-04, 7.93984619e-04, ...,
         8.46524712e-04, 7.89790215e-04, 7.97916601e-04]],

       [[1.49595753e-03, 1.42895262e-03, 1.34214122e-03, ...,
         1.26661823e-03, 1.34594705e-03, 1.47625903e-03],
        [6.58353948e-04, 5.96743092e-04, 5.42625178e-04, ...,
         6.07100571e-04, 4.88123952e-04, 5.53240171e-04],
        [4.97741775e-04, 

In [9]:
get_statistics(varPg_file, 'var(Pg)')

statistics on var(Pg):
max var(Pg):
1.379957e+01
min var(Pg):
6.197767e-25
percentile on var(Pg) [25%, 50%, 75%]:
[2.92105080e-13 2.72379103e-10 5.68285937e-07]
percentile on var(Pg) [10%, 90%]:
[1.51450496e-15 1.99489762e-04]


var($\rho$)

In [10]:
varRHO_file = np.load('ma_varRHO.npy', allow_pickle=True)
varRHO_file

array([[[6.47945533e-04, 6.15182690e-04, 5.86058680e-04, ...,
         6.56553355e-04, 6.54772267e-04, 6.61510982e-04],
        [1.10859498e-03, 1.10239673e-03, 1.10589745e-03, ...,
         1.20335020e-03, 1.16000436e-03, 1.15600446e-03],
        [7.41682818e-04, 7.50943387e-04, 7.42797261e-04, ...,
         8.67646111e-04, 8.68303972e-04, 7.80579690e-04],
        ...,
        [8.55684926e-04, 8.00888640e-04, 7.36752233e-04, ...,
         7.60243397e-04, 7.59089571e-04, 8.04305236e-04],
        [1.45246080e-03, 1.45586645e-03, 1.25102347e-03, ...,
         1.29578632e-03, 1.16485018e-03, 1.24461608e-03],
        [7.01973650e-04, 6.83509960e-04, 6.78921438e-04, ...,
         7.45772367e-04, 7.27561644e-04, 7.12308228e-04]],

       [[8.27562268e-04, 7.87457387e-04, 7.73716951e-04, ...,
         8.74032849e-04, 8.68693407e-04, 8.59195790e-04],
        [1.39141699e-03, 1.34867116e-03, 1.40117483e-03, ...,
         1.51822410e-03, 1.45741795e-03, 1.48763428e-03],
        [9.01067459e-04, 

In [11]:
get_statistics(varRHO_file, 'var(RHO)')

statistics on var(RHO):
max var(RHO):
1.577499e+02
min var(RHO):
2.686029e-19
percentile on var(RHO) [25%, 50%, 75%]:
[1.62159180e-09 1.24313563e-06 7.13746062e-04]
percentile on var(RHO) [10%, 90%]:
[3.01543114e-11 8.56374238e-02]


var($B^{2}$)

In [12]:
varbsq_file = np.load('ma_varbsq.npy', allow_pickle=True)
varbsq_file

array([[[5.44930753e+00, 5.43463682e+00, 5.43034670e+00, ...,
         5.50906051e+00, 5.49548110e+00, 5.47423282e+00],
        [5.11298103e+00, 5.14279973e+00, 5.15141761e+00, ...,
         5.21358314e+00, 5.14677526e+00, 5.10836362e+00],
        [3.86225779e+00, 3.83468057e+00, 3.81622170e+00, ...,
         3.94062242e+00, 3.90386613e+00, 3.88673869e+00],
        ...,
        [3.86456256e+00, 3.84723976e+00, 3.84371592e+00, ...,
         3.89894262e+00, 3.91158952e+00, 3.88962749e+00],
        [4.61524520e+00, 4.58040689e+00, 4.56787343e+00, ...,
         4.66398384e+00, 4.67164774e+00, 4.66128740e+00],
        [4.74270492e+00, 4.74816277e+00, 4.74331253e+00, ...,
         4.74143024e+00, 4.74166093e+00, 4.73775436e+00]],

       [[4.56752393e+00, 4.56010712e+00, 4.55986763e+00, ...,
         4.62112302e+00, 4.60594710e+00, 4.58743011e+00],
        [4.39379795e+00, 4.40386987e+00, 4.41720453e+00, ...,
         4.48475693e+00, 4.43009283e+00, 4.42463052e+00],
        [3.39950038e+00, 

In [13]:
get_statistics(varbsq_file, 'var(bsq)')

statistics on var(bsq):
max var(bsq):
6.179953e+01
min var(bsq):
3.067089e-30
percentile on var(bsq) [25%, 50%, 75%]:
[2.60320661e-13 1.32217021e-08 6.97967578e-05]
percentile on var(bsq) [10%, 90%]:
[1.95782551e-17 3.86021385e-02]


Covariance terms

In [14]:
ma_avg_Pg = np.load('ma_avgPg.npy', allow_pickle=True).item()['Pg']
ma_avg_RHO = np.load('ma_avgRHO.npy', allow_pickle=True).item()['RHO']
ma_avg_bsq = np.load('ma_avgbsq.npy', allow_pickle=True).item()['bsq']

In [15]:
ma_avgPgRHO = np.load('ma_avgRHOPg.npy', allow_pickle=True).item()['rhoPg']
ma_avgPgbsq = 2*mu*np.load('ma_avgPgPmag.npy', allow_pickle=True).item()['PgPmag']
ma_avgRHObsq = 2*mu*np.load('ma_avgRHOPmag.npy', allow_pickle=True).item()['rhoPmag']

In [16]:
ma_covPgRHO = ma_avgPgRHO - ma_avg_Pg * ma_avg_RHO
ma_covPgRHO

array([[[ 6.89314914e-04,  6.48585014e-04,  6.03590794e-04, ...,
          6.21128339e-04,  6.45898667e-04,  6.90854700e-04],
        [ 5.04169819e-04,  5.20304403e-04,  5.14412449e-04, ...,
          5.30785757e-04,  4.85777902e-04,  4.85205419e-04],
        [ 5.02273740e-04,  5.38030071e-04,  5.24877942e-04, ...,
          5.05337115e-04,  4.57863945e-04,  4.41015357e-04],
        ...,
        [ 4.92967079e-04,  4.43554257e-04,  4.41072502e-04, ...,
          5.34443111e-04,  5.29689014e-04,  5.26877143e-04],
        [ 7.20469076e-04,  7.11565936e-04,  6.07001709e-04, ...,
          4.75270097e-04,  4.28918373e-04,  5.45770657e-04],
        [ 6.61484530e-04,  6.49897692e-04,  6.73796272e-04, ...,
          6.81136054e-04,  6.53826715e-04,  6.53968768e-04]],

       [[ 1.02136050e-03,  9.69185575e-04,  9.36749190e-04, ...,
          9.57060694e-04,  9.93268683e-04,  1.03496339e-03],
        [ 6.91835704e-04,  7.11004615e-04,  7.32713427e-04, ...,
          7.57238928e-04,  6.30598179e

In [17]:
# wrong range
get_statistics(ma_covPgRHO, 'cov(PgRHO)')

statistics on cov(PgRHO):
max cov(PgRHO):
4.126740e+01
min cov(PgRHO):
-1.817373e-03
percentile on cov(PgRHO) [25%, 50%, 75%]:
[9.80148585e-12 6.61589981e-09 1.07192276e-05]
percentile on cov(PgRHO) [10%, 90%]:
[1.14239879e-14 2.90752251e-03]


In [18]:
ma_covPgbsq = ma_avgPgbsq - ma_avg_Pg * ma_avg_bsq
ma_covPgbsq

array([[[ 6.06903067e-02,  5.94129548e-02,  5.70372386e-02, ...,
          5.44891540e-02,  5.65506404e-02,  5.97835047e-02],
        [ 3.49104577e-02,  3.60118510e-02,  3.40518923e-02, ...,
          3.18285440e-02,  3.22427967e-02,  3.29148806e-02],
        [ 3.78340570e-02,  4.00985240e-02,  3.95554430e-02, ...,
          3.37420927e-02,  3.30712097e-02,  3.47152850e-02],
        ...,
        [ 3.65283548e-02,  3.51344815e-02,  3.47409242e-02, ...,
          4.21223375e-02,  4.13029474e-02,  3.88427028e-02],
        [ 3.23337143e-02,  3.39691900e-02,  3.31035213e-02, ...,
          2.17199043e-02,  2.13124306e-02,  2.60935975e-02],
        [ 5.08276835e-02,  5.11469291e-02,  5.33148928e-02, ...,
          5.22521728e-02,  5.06535111e-02,  5.03644103e-02]],

       [[ 7.66532353e-02,  7.50379708e-02,  7.35111212e-02, ...,
          7.10181547e-02,  7.35403679e-02,  7.60786689e-02],
        [ 4.00039151e-02,  4.01119035e-02,  3.75567150e-02, ...,
          4.00875716e-02,  3.57795561e

In [19]:
ma_covPgbsq.dtype

dtype('float64')

In [27]:
# wrong range
get_statistics(ma_covPgbsq, 'cov(Pgbsq)')

statistics on cov(Pgbsq):
max cov(Pgbsq):
8.479490e-02
min cov(Pgbsq):
-2.670889e+01
percentile on cov(Pgbsq) [25%, 50%, 75%]:
[-1.10025509e-07 -1.01110790e-14  6.21981044e-13]
percentile on cov(Pgbsq) [10%, 90%]:
[-3.06674735e-04  2.66050043e-08]


In [39]:
ma_covRHObsq = ma_avgRHObsq - ma_avg_RHO * ma_avg_bsq
ma_covRHObsq

array([[[ 5.44409335e-02,  5.31456474e-02,  5.21808463e-02, ...,
          5.50013644e-02,  5.48781190e-02,  5.50591208e-02],
        [ 6.45063926e-02,  6.57081163e-02,  6.53865403e-02, ...,
          6.54231410e-02,  6.31065855e-02,  6.31552768e-02],
        [ 4.83152183e-02,  4.81472844e-02,  4.81393079e-02, ...,
          5.35390245e-02,  5.17976684e-02,  4.94868091e-02],
        ...,
        [ 4.81762612e-02,  4.69964184e-02,  4.64315047e-02, ...,
          4.90814186e-02,  4.92557087e-02,  4.87428955e-02],
        [ 6.61202289e-02,  6.82814868e-02,  6.62994896e-02, ...,
          6.28530873e-02,  6.02973743e-02,  6.19543013e-02],
        [ 5.34672555e-02,  5.31637079e-02,  5.35262406e-02, ...,
          5.43226934e-02,  5.39885823e-02,  5.37597602e-02]],

       [[ 5.75798492e-02,  5.60031878e-02,  5.59307822e-02, ...,
          5.96932456e-02,  5.94677881e-02,  5.88767204e-02],
        [ 6.67898072e-02,  6.72564786e-02,  6.75129161e-02, ...,
          6.96555537e-02,  6.61982868e

In [40]:
# wrong range
get_statistics(ma_covRHObsq, 'cov(RHObsq)')

statistics on cov(RHObsq):
max cov(RHObsq):
3.975133e-01
min cov(RHObsq):
-8.013672e+01
percentile on cov(RHObsq) [25%, 50%, 75%]:
[-4.43781227e-06 -3.01207338e-14  4.45367632e-10]
percentile on cov(RHObsq) [10%, 90%]:
[-5.10990959e-03  2.82974528e-06]


Coefficients

In [18]:
ma_CPg1 = np.load('ma_CPg1.npy')
ma_CPg1

array([[[9.35837869e+12, 9.35990743e+12, 9.35825254e+12, ...,
         9.37692947e+12, 9.37660668e+12, 9.36548653e+12],
        [7.25238669e+12, 7.26028104e+12, 7.27015063e+12, ...,
         7.28802521e+12, 7.28238427e+12, 7.26537522e+12],
        [9.08909431e+12, 9.09827389e+12, 9.07407731e+12, ...,
         9.04534675e+12, 9.04295831e+12, 9.06428824e+12],
        ...,
        [9.01359109e+12, 9.04986984e+12, 9.05488161e+12, ...,
         8.97185766e+12, 9.00214371e+12, 9.00577135e+12],
        [7.30693405e+12, 7.26952073e+12, 7.25775227e+12, ...,
         7.25482074e+12, 7.27127677e+12, 7.30492981e+12],
        [9.36826231e+12, 9.36424559e+12, 9.36692161e+12, ...,
         9.33472542e+12, 9.35179003e+12, 9.36727681e+12]],

       [[8.06927982e+12, 8.06362060e+12, 8.06225947e+12, ...,
         8.06323765e+12, 8.06981964e+12, 8.07275838e+12],
        [6.33768330e+12, 6.34065773e+12, 6.36324318e+12, ...,
         6.38610630e+12, 6.38565212e+12, 6.36107845e+12],
        [8.51749866e+12, 

In [19]:
get_statistics(ma_CPg1, 'C[Pg->Te]')

statistics on C[Pg->Te]:
max C[Pg->Te]:
5.748793e+18
min C[Pg->Te]:
2.752108e+11
percentile on C[Pg->Te] [25%, 50%, 75%]:
[3.76190673e+13 3.32959423e+14 5.56979124e+15]
percentile on C[Pg->Te] [10%, 90%]:
[1.09451467e+13 3.64389822e+16]


In [20]:
ma_Crho1 = np.load('ma_Crho1.npy')
ma_Crho1

array([[[-9.30320531e+12, -9.31191185e+12, -9.32149250e+12, ...,
         -9.23876222e+12, -9.28899914e+12, -9.30402068e+12],
        [-3.39330931e+12, -3.39275984e+12, -3.40214262e+12, ...,
         -3.40271353e+12, -3.40558596e+12, -3.40048238e+12],
        [-6.84747971e+12, -6.84662025e+12, -6.83847289e+12, ...,
         -6.84844875e+12, -6.81550268e+12, -6.82354969e+12],
        ...,
        [-6.89623647e+12, -6.91839626e+12, -6.90239745e+12, ...,
         -6.82941091e+12, -6.86927934e+12, -6.87254460e+12],
        [-3.34178115e+12, -3.35766318e+12, -3.36841585e+12, ...,
         -3.30227544e+12, -3.30483864e+12, -3.32183156e+12],
        [-9.13354840e+12, -9.13995557e+12, -9.12840763e+12, ...,
         -9.07506733e+12, -9.09333502e+12, -9.11623146e+12]],

       [[-9.55493581e+12, -9.55803548e+12, -9.55638476e+12, ...,
         -9.47639927e+12, -9.51989867e+12, -9.54220936e+12],
        [-3.25858569e+12, -3.24686011e+12, -3.24458908e+12, ...,
         -3.26365043e+12, -3.26829698e

In [21]:
get_statistics(ma_Crho1, 'C[RHO->Te]')

statistics on C[RHO->Te]:
max C[RHO->Te]:
-4.593311e+10
min C[RHO->Te]:
-1.257640e+17
percentile on C[RHO->Te] [25%, 50%, 75%]:
[-5.05106355e+13 -3.17239403e+12 -3.16068016e+11]
percentile on C[RHO->Te] [10%, 90%]:
[-1.24598361e+15 -1.43186456e+11]


In [22]:
ma_Cbsq1 = np.load('ma_Cbsq1.npy')
ma_Cbsq1

array([[[2.26660482e+09, 2.27042416e+09, 2.27724501e+09, ...,
         2.22235659e+09, 2.24714615e+09, 2.26190064e+09],
        [6.68409516e+08, 6.66555350e+08, 6.67910255e+08, ...,
         6.61932161e+08, 6.64701562e+08, 6.67617439e+08],
        [1.60082203e+09, 1.59594497e+09, 1.60604605e+09, ...,
         1.62384786e+09, 1.61266549e+09, 1.60461903e+09],
        ...,
        [1.65767226e+09, 1.64676316e+09, 1.63415664e+09, ...,
         1.64290250e+09, 1.64665112e+09, 1.64877454e+09],
        [6.32715766e+08, 6.49177732e+08, 6.56818375e+08, ...,
         6.33418837e+08, 6.29733274e+08, 6.26422307e+08],
        [2.18931944e+09, 2.19528757e+09, 2.18682515e+09, ...,
         2.18444126e+09, 2.18181993e+09, 2.18175551e+09]],

       [[4.43863609e+09, 4.45285401e+09, 4.45524948e+09, ...,
         4.37544031e+09, 4.40515906e+09, 4.42027688e+09],
        [1.08721301e+09, 1.07797113e+09, 1.06467042e+09, ...,
         1.06371171e+09, 1.06824867e+09, 1.07952628e+09],
        [1.60893431e+09, 

In [23]:
get_statistics(ma_Cbsq1, 'C[bsq->Te]')

statistics on C[bsq->Te]:
max C[bsq->Te]:
2.201879e+17
min C[bsq->Te]:
1.081829e+07
percentile on C[bsq->Te] [25%, 50%, 75%]:
[1.74378823e+11 1.10908615e+13 2.37927629e+14]
percentile on C[bsq->Te] [10%, 90%]:
[2.43946473e+09 3.73462874e+15]
